### FFZ_RecentBroadcasts

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FFZ_RecentBroadcasts",
  "variables": {
    "id": "106013742",
    "type": "ARCHIVE",
    "sort": "TIME",
    "limit": 10
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "a92c0ad34fdba9b3f5e6125dce4b0acc9373f2b2c06c74c92187749d12f73d4c"
    }
  }
}
