### GetPinnedChat

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "GetPinnedChat",
  "variables": {
    "channelID": "71092938",
    "count": 1
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "2d099d4c9b6af80a07d8440140c4f3dbb04d516b35c401aab7ce8f60765308d5"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "GetPinnedChat",
  "variables": {
    "channelID": "channel-not-exists",
    "count": 1
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "2d099d4c9b6af80a07d8440140c4f3dbb04d516b35c401aab7ce8f60765308d5"
    }
  }
}
