### UseLive

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "UseLive",
  "variables": {
    "channelLogin": "summit1g"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "639d5f11bfb8bf3053b424d9ef650d04c4ebb7d94711d644afb08fe9a0fad5d9"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "UseLive",
  "variables": {
    "channelLogin": "user-not-exists"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "639d5f11bfb8bf3053b424d9ef650d04c4ebb7d94711d644afb08fe9a0fad5d9"
    }
  }
}
