# FilterableVideoTower_Videos

### all variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "includePreviewBlur": false,
    "limit": 30,
    "channelOwnerLogin": "twitch",
    "broadcastType": "ARCHIVE",
    "videoSort": "TIME"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}

### only required variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "limit": 30,
    "channelOwnerLogin": "twitch",
    "videoSort": "TIME"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}

### broadcastType: ARCHIVE

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "includePreviewBlur": false,
    "limit": 30,
    "channelOwnerLogin": "twitch",
    "broadcastType": "ARCHIVE",
    "videoSort": "TIME"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}

### broadcastType: HIGHLIGHT

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "includePreviewBlur": false,
    "limit": 30,
    "channelOwnerLogin": "summit1g",
    "broadcastType": "HIGHLIGHT",
    "videoSort": "VIEWS"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}

### broadcastType: UPLOAD

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "includePreviewBlur": false,
    "limit": 30,
    "channelOwnerLogin": "twitch",
    "broadcastType": "UPLOAD",
    "videoSort": "TIME"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}

### broadcastType: null (all videos)

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "includePreviewBlur": false,
    "limit": 30,
    "channelOwnerLogin": "twitch",
    "broadcastType": null,
    "videoSort": "TIME"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}

### includePreviewBlur: true

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "includePreviewBlur": true,
    "limit": 30,
    "channelOwnerLogin": "twitch",
    "broadcastType": "ARCHIVE",
    "videoSort": "TIME"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}

### channel not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "FilterableVideoTower_Videos",
  "variables": {
    "includePreviewBlur": false,
    "limit": 30,
    "channelOwnerLogin": "-channel-not-exists-",
    "broadcastType": null,
    "videoSort": "TIME"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "67004f7881e65c297936f32c75246470629557a393788fb5a69d6d9a25a8fd5f"
    }
  }
}
