# ChannelVideoShelvesQuery

### all variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ChannelVideoShelvesQuery",
  "variables": {
    "includePreviewBlur": false,
    "channelLogin": "twitch",
    "first": 5
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "280f582866d0914749c1666da7adfcdb42739182b060ef4050641aa9324da19b"
    }
  }
}

### only required variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ChannelVideoShelvesQuery",
  "variables": {
    "channelLogin": "twitch",
    "first": 5
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "280f582866d0914749c1666da7adfcdb42739182b060ef4050641aa9324da19b"
    }
  }
}

### includePreviewBlur: true

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ChannelVideoShelvesQuery",
  "variables": {
    "includePreviewBlur": true,
    "channelLogin": "twitch",
    "first": 5
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "280f582866d0914749c1666da7adfcdb42739182b060ef4050641aa9324da19b"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ChannelVideoShelvesQuery",
  "variables": {
    "includePreviewBlur": false,
    "channelLogin": "-channel-not-exists-",
    "first": 5
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "280f582866d0914749c1666da7adfcdb42739182b060ef4050641aa9324da19b"
    }
  }
}
