# ClipsCards__Game

### all variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__Game",
  "variables": {
    "categorySlug": "just-chatting",
    "limit": 20,
    "criteria": {
      "languages": [],
      "filter": "LAST_WEEK",
      "shouldFilterByDiscoverySetting": true
    },
    "cursor": null
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "ebcf54afb9aa5d6cec8aad2c35b84e2737a109dac5b184308aae73a27d176707"
    }
  }
}

### only required variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__Game",
  "variables": {
    "categorySlug": "just-chatting",
    "limit": 20
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "ebcf54afb9aa5d6cec8aad2c35b84e2737a109dac5b184308aae73a27d176707"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__Game",
  "variables": {
    "categorySlug": "-category-not-exists-",
    "limit": 20
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "ebcf54afb9aa5d6cec8aad2c35b84e2737a109dac5b184308aae73a27d176707"
    }
  }
}

### integrity error

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__Game",
  "variables": {
    "categorySlug": "just-chatting",
    "limit": 20,
    "cursor": "MjA="
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "ebcf54afb9aa5d6cec8aad2c35b84e2737a109dac5b184308aae73a27d176707"
    }
  }
}
