# ShareClipRenderStatus

### with portrait

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "UnusualEnchantingSproutGivePLZ-o5o0fw_2qOgZvAag"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "0a02bb974443b576f5579aab0fef1d4b7f44e58a8a256f0c5adfead0db70640f"
    }
  }
}

### no broadcaster

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "ShakingBlitheOwlBrokeBack"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "0a02bb974443b576f5579aab0fef1d4b7f44e58a8a256f0c5adfead0db70640f"
    }
  }
}

### no game

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "AstuteEncouragingCroquetteJebaited"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "0a02bb974443b576f5579aab0fef1d4b7f44e58a8a256f0c5adfead0db70640f"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "not-exists"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "0a02bb974443b576f5579aab0fef1d4b7f44e58a8a256f0c5adfead0db70640f"
    }
  }
}

### 1440p

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "TenaciousOriginalMooseNononoCat-AEuwlukHCpsIR0wn"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "0a02bb974443b576f5579aab0fef1d4b7f44e58a8a256f0c5adfead0db70640f"
    }
  }
}

### HEVC

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "DeliciousCarelessCrowLitty-ccS0mlymOKwRZBjV"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "0a02bb974443b576f5579aab0fef1d4b7f44e58a8a256f0c5adfead0db70640f"
    }
  }
}
