### ShareClipRenderStatus

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "PoorCulturedInternRitzMitz-zMyZG0y18jO0AJ58"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "e0a46b287d760c6890a39d1ccd736af5ec9479a267d02c710e9ac33326b651d2"
    }
  }
}

### no broadcaster

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "ShakingBlitheOwlBrokeBack"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "e0a46b287d760c6890a39d1ccd736af5ec9479a267d02c710e9ac33326b651d2"
    }
  }
}

### no game

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "AstuteEncouragingCroquetteJebaited"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "e0a46b287d760c6890a39d1ccd736af5ec9479a267d02c710e9ac33326b651d2"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "not-exists"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "e0a46b287d760c6890a39d1ccd736af5ec9479a267d02c710e9ac33326b651d2"
    }
  }
}

### 1440p

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "TenaciousOriginalMooseNononoCat-AEuwlukHCpsIR0wn"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "e0a46b287d760c6890a39d1ccd736af5ec9479a267d02c710e9ac33326b651d2"
    }
  }
}

### HEVC

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ShareClipRenderStatus",
  "variables": {
    "slug": "DeliciousCarelessCrowLitty-ccS0mlymOKwRZBjV"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "e0a46b287d760c6890a39d1ccd736af5ec9479a267d02c710e9ac33326b651d2"
    }
  }
}
