### VideoAccessToken_Clip

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "VideoAccessToken_Clip",
  "variables": {
    "slug": "DeliciousDelightfulPicklesWOOP"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "36b89d2507fce29e5ca551df756d27c1cfe079e2609642b4390aa4c35796eb11"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "VideoAccessToken_Clip",
  "variables": {
    "slug": "not-exists"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "36b89d2507fce29e5ca551df756d27c1cfe079e2609642b4390aa4c35796eb11"
    }
  }
}
