# VideoMetadata

### archive

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "VideoMetadata",
  "variables": {
    "channelLogin": "twitch",
    "videoID": "2404782496"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "45111672eea2e507f8ba44d101a61862f9c56b11dee09a15634cb75cb9b9084d"
    }
  }
}

### highlight

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "VideoMetadata",
  "variables": {
    "channelLogin": "twitch",
    "videoID": "2097305181"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "45111672eea2e507f8ba44d101a61862f9c56b11dee09a15634cb75cb9b9084d"
    }
  }
}

### upload

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "VideoMetadata",
  "variables": {
    "channelLogin": "twitch",
    "videoID": "2185567716"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "45111672eea2e507f8ba44d101a61862f9c56b11dee09a15634cb75cb9b9084d"
    }
  }
}

### empty channelLogin

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "VideoMetadata",
  "variables": {
    "channelLogin": "",
    "videoID": "2404782496"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "45111672eea2e507f8ba44d101a61862f9c56b11dee09a15634cb75cb9b9084d"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "VideoMetadata",
  "variables": {
    "channelLogin": "",
    "videoID": "2185567717"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "45111672eea2e507f8ba44d101a61862f9c56b11dee09a15634cb75cb9b9084d"
    }
  }
}
