### ChannelShell

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ChannelShell",
  "variables": {
    "login": "twitch"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "580ab410bcd0c1ad194224957ae2241e5d252b2c5173d8e0cce9d32d5bb14efe"
    }
  }
}
