### UseUseViewCount

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "UseViewCount",
  "variables": {
    "channelLogin": "summit1g"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "00b11c9c428f79ae228f30080a06ffd8226a1f068d6f52fbc057cbde66e994c2"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "UseViewCount",
  "variables": {
    "channelLogin": "not-exists"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "00b11c9c428f79ae228f30080a06ffd8226a1f068d6f52fbc057cbde66e994c2"
    }
  }
}
