# SearchResultsPage_SearchResults

### all variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "platform": "web",
    "query": "action",
    "options": {
      "targets": null,
      "shouldSkipDiscoveryControl": false
    },
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}

### only required variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "query": "forsen",
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}

### shouldSkipDiscoveryControl: true

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "platform": "web",
    "query": "asmr",
    "options": {
      "targets": null,
      "shouldSkipDiscoveryControl": true
    },
    "includeIsDJ": false
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}

### includeIsDJ: false

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "platform": "web",
    "query": "moba",
    "options": {
      "targets": null,
      "shouldSkipDiscoveryControl": false
    },
    "includeIsDJ": false
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}

### targets: CHANNEL (with schedule)

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "platform": "web",
    "query": "cohhcarnage",
    "options": {
      "targets": [
        { "index": "CHANNEL" }
      ],
      "shouldSkipDiscoveryControl": false
    },
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}

### targets: CHANNEL_WITH_TAG

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "platform": "web",
    "query": "forsen",
    "options": {
      "targets": [
        { "index": "CHANNEL_WITH_TAG" }
      ],
      "shouldSkipDiscoveryControl": false
    },
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}


### targets: GAME

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "platform": "web",
    "query": "monster",
    "options": {
      "targets": [
        { "index": "GAME" }
      ],
      "shouldSkipDiscoveryControl": false
    },
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}

### targets: VOD

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "SearchResultsPage_SearchResults",
  "variables": {
    "platform": "web",
    "query": "gtnh",
    "options": {
      "targets": [
        { "index": "VOD" }
      ],
      "shouldSkipDiscoveryControl": false
    },
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "f6c2575aee4418e8a616e03364d8bcdbf0b10a5c87b59f523569dacc963e8da5"
    }
  }
}
