# ClipsCards__User

### all variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__User",
  "variables": {
    "login": "xqc",
    "limit": 20,
    "criteria": {
      "filter": "LAST_WEEK",
      "shouldFilterByDiscoverySetting": true
    },
    "cursor": null
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "1cd671bfa12cec480499c087319f26d21925e9695d1f80225aae6a4354f23088"
    }
  }
}

### only required variables

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__User",
  "variables": {
    "login": "xqc",
    "limit": 20
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "1cd671bfa12cec480499c087319f26d21925e9695d1f80225aae6a4354f23088"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__User",
  "variables": {
    "login": "-user-not-exists-",
    "limit": 20
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "1cd671bfa12cec480499c087319f26d21925e9695d1f80225aae6a4354f23088"
    }
  }
}

### integrity error

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsCards__User",
  "variables": {
    "login": "xqc",
    "limit": 20,
    "cursor": "MjA="
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "1cd671bfa12cec480499c087319f26d21925e9695d1f80225aae6a4354f23088"
    }
  }
}
