### ChatList_Badges

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ChatList_Badges",
  "variables": {
    "channelLogin": "xqc"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "838a7e0b47c09cac05f93ff081a9ff4f876b68f7624f0fc465fe30031e372fc2"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ChatList_Badges",
  "variables": {
    "channelLogin": "user-not-exists"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "838a7e0b47c09cac05f93ff081a9ff4f876b68f7624f0fc465fe30031e372fc2"
    }
  }
}
