### ClipsActionButtons

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsActionButtons",
  "variables": {
    "slug": "WrongSplendidWrenYouDontSay-0Pkulh5IfiMkLH_P"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "c10c0319f1b62107ffaf542f36d82c58db3cdf7451379910fe27c45bac889ab4"
    }
  }
}

### no broadcaster

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsActionButtons",
  "variables": {
    "slug": "ShakingBlitheOwlBrokeBack"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "c10c0319f1b62107ffaf542f36d82c58db3cdf7451379910fe27c45bac889ab4"
    }
  }
}

### no game

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsActionButtons",
  "variables": {
    "slug": "AstuteEncouragingCroquetteJebaited"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "c10c0319f1b62107ffaf542f36d82c58db3cdf7451379910fe27c45bac889ab4"
    }
  }
}

### not exists

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "ClipsActionButtons",
  "variables": {
    "slug": "hello-world"
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "c10c0319f1b62107ffaf542f36d82c58db3cdf7451379910fe27c45bac889ab4"
    }
  }
}
