### StreamMetadata

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "StreamMetadata",
  "variables": {
    "channelLogin": "xqc",
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "b57f9b910f8cd1a4659d894fe7550ccc81ec9052c01e438b290fd66a040b9b93"
    }
  }
}

### includeIsDJ: false

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "StreamMetadata",
  "variables": {
    "channelLogin": "xqc",
    "includeIsDJ": false
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "b57f9b910f8cd1a4659d894fe7550ccc81ec9052c01e438b290fd66a040b9b93"
    }
  }
}

### never streamed

POST https://gql.twitch.tv/gql
Content-Type: application/json
Client-Id: {{$dotenv CLIENT_ID}}

{
  "operationName": "StreamMetadata",
  "variables": {
    "channelLogin": "xqcbot",
    "includeIsDJ": true
  },
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "b57f9b910f8cd1a4659d894fe7550ccc81ec9052c01e438b290fd66a040b9b93"
    }
  }
}
